# Этап сборки
FROM ubuntu:22.04 AS builder
RUN apt-get update && apt-get install -y clang make

WORKDIR /app
# Копирование исходного кода
COPY Makefile .
COPY src/ ./src/

# Компиляция нужного таргета (broker, producer или consumer)
RUN make build/broker

# Этап выполнения
FROM ubuntu:22.04
WORKDIR /app

# Копирование только готового бинарного файла из этапа сборки
COPY --from=builder /app/build/broker .

# Пример запуска с передачей аргументов
ENTRYPOINT ["./broker"]