services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile.broker
    command: ["--host", "0.0.0.0", "--port", "5001"]
    ports:
      - "5001:5001"
    volumes:
      - ./output:/app/output
    networks: [lab_net]

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: ["--host", "broker", "--port", "5001"]
    restart: on-failure
    depends_on:
      - broker
    networks: [lab_net]

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    command: ["--host", "broker", "--port", "5001"]
    volumes:
      - ./images:/app/images
    depends_on:
      - broker
    networks: [lab_net]

networks:
  lab_net:
    driver: bridge