FROM ubuntu:22.04 AS builder
RUN apt-get update && apt-get install -y g++ make

WORKDIR /app
COPY Makefile .
COPY src/ ./src/

RUN make build/broker

FROM ubuntu:22.04
WORKDIR /app
COPY --from=builder /app/build/broker .

ENTRYPOINT ["./broker"]